spring.application.name=connectong-api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://143.106.241.3:3306/cl203161
spring.datasource.username=cl203161
spring.datasource.password=cl*28032008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true